bookr/urls.py
from django.contrib import admin
from django.urls import path,include
from reviews.admin import admin_site
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    
    path('',include('reviews.urls')),
    
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  
    

reviews/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.index,name="index"),
    path('search/',views.book_search, name="search"),
    path('details/<int:id>/',views.details, name="details"),
    path('download-pdf/<int:pk>/',views.download, name="download_pdf"),

    path('form/',views.form_example, name="form_example"),
    path('profile/<int:id>/',views.userprofile, name="profile"),
    path('profile/details/<int:book_id>/',views.BookDetails ,name="book_details"),
    path('profile/delete/<int:id>',views.deleteBook, name="delete"),
    path('profile/update/<int:id>',views.updateBook, name="update"),
    path('profile/upload/<int:user_id>',views.uploadBook, name="upload"),
    path('blog/<slug:slug>', views.blogdetails,name ="blog"),
    
    path('login/',views.loginform, name="login"),
    path('register/',views.registerform, name="register"),
    
    path('logout',views.logoutform, name="logout"),
    
]

reviews/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.

class Profile(models.Model):
    profileImage = models.ImageField(default='',upload_to='profile/')
    user = models.OneToOneField(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.user
        
class Publisher(models.Model):
    
    """ A company that publishes books. """

    name = models.CharField(max_length=50,help_text="The name of the Publisher.")
    website = models.URLField(
    help_text="The Publisher's website.")
    email = models.EmailField(help_text="The Publisher's email address.")
    
    def __str__(self):
        
        return self.name
     
    
    
class Book(models.Model):
    """A published book."""
    title = models.CharField(
        max_length=100, help_text="The title of the book.")
    publication_date = models.DateField(
        verbose_name="Date the book was published.")
    isbn = models.CharField(max_length=20, verbose_name="ISBN number of the book.")
    cover = models.ImageField(upload_to='covers/',null=True)
    file_field = models.FileField(upload_to="files/",null=True,blank=True)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    contributors = models.ManyToManyField('Contributor', through="BookContributor")
    featured = models.BooleanField(default=False)
    uploader = models.ForeignKey(User,on_delete=models.CASCADE, default='',null=True)
    date_uploaded = models.DateField(auto_now_add=True, null= True)
    
    
    

    def __str__ (self):
        return self.title


class Contributor(models.Model):
    """A contributor to a Book, e.g. author, editor,
    co-author."""
    first_names = models.CharField(
    max_length=50, help_text="The contributor's first name or names.")
    last_names = models.CharField(
    max_length=50, help_text="The contributor's last name or names.")
    email = models.EmailField(help_text="The contact email for the contributor.")
    
    def __str__ (self):
        return self.first_names + ' ' + self.last_names
    
class BookContributor(models.Model):
    class ContributionRole(models.TextChoices):
        AUTHOR = "AUTHOR", "Author"
        CO_AUTHOR = "CO_AUTHOR", "Co-Author"
        EDITOR = "EDITOR", "Editor"
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE,related_name='book')
    contributor = models.ForeignKey(
        Contributor, on_delete=models.CASCADE)
    role = models.CharField(
        verbose_name="The role this contributor had in the book.", choices=ContributionRole.choices,
        max_length=20)
    
    
    def __str__(self):
        return str(self.contributor) + ' ' + self.role
        
    
class Review(models.Model):
    content = models.TextField(
help_text="The Review text.")
    rating = models.IntegerField(
help_text="The rating the reviewer has given.")
    date_created = models.DateTimeField(
auto_now_add=True,
help_text="The date and time the review was \
created.")
    
    date_edited = models.DateTimeField(
null=True, help_text="The date and time the review \
was last edited.")
    creator = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE)
    book = models.ForeignKey(
Book, on_delete=models.CASCADE,
    help_text="The Book that this review is for.")
    
    
    def __str__(self):
        
        return self.content
    class Meta:
        unique_together = ('book','creator')
        
        
class Blog(models.Model):
    title = models.CharField(max_length=250,help_text="Title of the Blog", verbose_name="Blog Title")
    contents = models.TextField(help_text="Blog contents" ,verbose_name="Blog Content")
    date_created = models.DateTimeField(auto_now=True, help_text="Date Created",verbose_name="Date Created")
    date_updated = models.DateTimeField(auto_now_add=True,help_text="Date Updated")
    images = models.ImageField(upload_to='Blog', help_text="Image of the Blog")
    user = models.ForeignKey(User, on_delete= models.CASCADE,help_text="The user who created The blog")
    slug = models.SlugField(unique=True, verbose_name="slug")
    
    class Meta:
        verbose_name_plural = 'Blog'
    
    def save(self,*args, **kwargs):
        
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    
    

reviews/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Book


class SearchForm(forms.Form):
    Choices = (
        ('Title','Title'),
        ('ISBN','ISBN'),
        ('Contributor','Contributor')
    )
    
    search_options = forms.ChoiceField(choices = Choices)
    
class Registrationform(forms.Form):
   username = forms.CharField(max_length=50, required=False,widget=forms.TextInput(attrs={'class':'form form-control form-floating'}))
   email = forms.EmailField(max_length=50, required=False,widget=forms.TextInput(attrs={'class':'form form-control form-floating'}))
   password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form form-control form-floating'}))
   confirm_password= forms.CharField(widget=forms.PasswordInput(attrs={'class':'form form-control form-floating'}))
   
   
   def clean(self):
       cleaned_data = super().clean()
       password = cleaned_data.get('password')
       confirm_password = cleaned_data.get('confirm_password')
       
       if password and confirm_password and password != confirm_password:
           raise forms.ValidationError("passwords do not match")
       
   def save(self):
       username = self.cleaned_data.get('username')
       email = self.cleaned_data.get('email')
       password = self.cleaned_data.get('password')
       
       user = User.objects.create_user(username=username,email=email,password=password)
       
       
       return user

       

class UpdateForm(forms.ModelForm):
        
       
       class Meta:
           model = Book
           fields = ("title","publication_date","isbn","cover","file_field","publisher")
           
           
class UploadForm(forms.ModelForm):
    
    class Meta:
        model = Book
        fields = ("title","publication_date","isbn","cover","file_field","publisher")
        
           
           
   

reviews/views.py
import os
from django.shortcuts import redirect, render, get_object_or_404
from .models import Book,Review,Contributor,BookContributor,Blog
from .utils import average_rating
from .forms import SearchForm,Registrationform,UpdateForm,UploadForm
from django.http import FileResponse, HttpResponse
from django.conf import settings
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .ratings import ratingCalc
from django.contrib import messages

def index(request):
        book = Book.objects.all()
        contributor = Contributor.objects.all()
        featured = Book.objects.filter(featured = True)
        new_arrivals = Book.objects.order_by('-publication_date')[:8]
        blog = Blog.objects.all()
        context = {
            'book':book,
            'featured':featured,
            'new_arrivals':new_arrivals,
            'blog':blog
        }
        return render(request, "reviews/index.html",context)
    
def book_search(request):
    if request.method == 'GET':
        search_text = request.GET.get("q")
       
        if search_text:
        
            query = Book.objects.filter(title__icontains = search_text)
            return render(request,"reviews/search-results.html",{"search_text": search_text,"query": query})
    
        else:
            return render(request,'reviews/search-results.html',{"search_text": search_text})
    else:
            return render(request,'reviews/search-results.html')
    
        


def details(request,id):
    books = Book.objects.get(id=id)
    cont = books.book.all()
    allBooks = Book.objects.all().exclude(id=id)[:3]
    return render(request,'reviews/details.html',{'books':books,
                                                  'cont':cont,
                                                  'allBooks':allBooks})
    
@login_required
def userprofile(request,id):
    
    profile = request.user
    uploaded_books = Book.objects.filter(uploader=profile)
    book_count = Book.objects.filter(uploader=profile).count()
    context = {
        'profile':profile,
        'uploaded_books':uploaded_books,
        'book_count':book_count
    }
    return render(request,'reviews/profile.html',context)
    
def download(request,pk):
    
    instance = get_object_or_404(Book,pk=pk)
    
    if instance.file_field:
        file = instance.file_field.file
        response = FileResponse(file,content_type='application/pdf')
        
       
        response['Content-Disposition'] = f'attachment; filename="{instance.file_field.name}"'
        return response
    
    return HttpResponse("not found")

@login_required
def updateBook(request,id):
    book = Book.objects.get(id=id)
    if request.user != book.uploader:
        return redirect('profile')
    
    if request.method == 'POST':
       form = UpdateForm(request.POST,request.FILES, instance=book) 
       if form.is_valid():
           form.save()
           return redirect('profile')
     
    else:
       form = UpdateForm(instance=book) 
        
    
    return render(request,'reviews/update.html',{'form':form,'book':book})   
    
    
def BookDetails(request,book_id):
    books = Book.objects.get(id=book_id)
    
    
    return render(request,'reviews/bookdetails.html',{'books':books})

@login_required
def deleteBook(request,id):
    book = Book.objects.get(id=id)
    book.delete()
    return redirect('profile')

@login_required
def uploadBook(request,user_id):
       
    user = User.objects.get(id=user_id)
    
    if request.method == 'POST':
        form = UploadForm(request.POST,request.FILES)
        if form.is_valid():
            book = form.save(commit=False)
            book.uploader = request.user
            book.save()
            return redirect('profile')
           
   
    else:
        
        form = UploadForm()
    
    return render(request,'reviews/upload.html',{'form':form})


def form_example(request):
    
    return render(request, "reviews/forms.html")


def loginform(request):
    
    username = request.POST.get('username')
    password = request.POST.get('password')
    
    user = authenticate(request,username=username,password=password)
    
    if user is not None:
        login(request,user)
        return redirect('index')
    else:
          
        return render(request,"reviews/login.html")
    
    return render(request, "reviews/login.html")
    
def registerform(request):
    if request.method == 'POST':
        form = Registrationform(request.POST)
    
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            login(request,user)
            
            return redirect('index')
    else:
            
            form = Registrationform()
        
  
        
    return render(request,'reviews/register.html', {'form':form})    
    
    


def logoutform(request):
    logout(request)
    return redirect('login')


def blogdetails(request,slug):
    blog = Blog.objects.get(id=slug)
    context = {
        'blog':blog
    }
    
    return render(request, 'reviews/blog.html',context)
    

#rating = [4,5,3,5,2]

#percentage_rating = ratingCalc(rating)
#print(percentage_rating)

reviews/templates/reviews/base.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title> {% block title %}Base HTML{% endblock title %} </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bs.css' %}">
        <link rel="stylesheet" href="{% static 'css/index.css' %}">

    </head>
{% block style %}

{% endblock style %}

    <body>
      
       
        <div class="container">
            {% block header %}
            <header>
                {% if user.is_authenticated %}
                <div class="px-3 py-2 bg-dark text-white">
                  <div class="container">
                    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                      <a href="{% url 'index' %}" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
                        <h3>Bookr Books</h3>
                      </a>
            
                      <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
                        <li>
                            <a href="{% url 'index' %}" class="nav-link text-secondary">

                            <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#home"/></svg>
                            Home
                          </a>
                        </li>
                        <li>
                          <a href="{% url 'profile' user.id %}" class="nav-link text-white">
                            <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#speedometer2"/></svg>
                            Profile
                          </a>
                        </li>
                        <li>
                          <a href="#" class="nav-link text-white">
                            <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#table"/></svg>
                            Contact
                          </a>
                        </li>
                        <li>
                          <a href="#" class="nav-link text-white">
                            <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#grid"/></svg>
                            About Us
                          </a>
                        </li>
                       
                      </ul>
                    </div>
                  </div>
                </div>
{% else %}

<div class="px-3 py-2 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="{% url 'index' %}" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <h3>Bookr Books</h3>
         
        </a>

        <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
          <li>
            <a href="{% url 'index' %}" class="nav-link text-secondary">
              <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#home"/></svg>
              Home
            </a>
          </li>
          
          <li>
            <a href="#" class="nav-link text-white">
              <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#table"/></svg>
              Contact
            </a>
          </li>
          <li>
            <a href="#" class="nav-link text-white">
              <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#grid"/></svg>
              About Us
            </a>
          </li>
         
        </ul>
      </div>
    </div>
  </div>

{% endif %}
                <div class="px-3 py-2 border-bottom mb-3">
                  <div class="container d-flex flex-wrap justify-content-center">
                    <form class="d-flex  col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto" method="GET" action="{% url 'search' %}">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-primary" type="submit">Search</button>
                      </form>
                     
                    <div class="text-end">
                        {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}" class="btn btn-primary text-dark me-2">Logout</a>

                        {% else %}
                      <a href="{% url 'login' %}" class="btn btn-light text-dark me-2">Login</a>
                      <a href="{% url 'register' %}" class="btn btn-primary">Sign-up</a>

                      {% endif %}
                    </div>
                  </div>
                </div>
              </header>
              {% endblock header %}
        
        
              {% block contents %}
        {% endblock contents %}
        

{% block footer %}
<div class="b-example-divider"></div>
<div class="container">
  <footer class="row row-cols-5 py-5 my-5 border-top">
    <div class="col">
      <a href="{% url 'index' %}" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      </a>
      <p class="text-muted">&copy; 2023</p>
    </div>

    <div class="col">

    </div>

    <div class="col">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
      </ul>
    </div>

    <div class="col">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
      </ul>
    </div>

    <div class="col">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
      </ul>
    </div>
  </footer>
</div>
</div>
{% endblock footer %}

        <script src="" async defer></script>
    </body>
</html>

reviews/templates/reviews/bookdetails.html
{% extends 'reviews/base.html' %}

{% block title %} {{books.title}} {% endblock title %}
{% block contents %}
<div class="container">
<p>
    <h3>Book Title:{{books.title}}</h3></p>
<br>
<p>Publication Date: {{books.publication_date}}</p>
<br>
<p>ISBN: {{books.isbn}}</p>
<p> 
    <h3>Book Cover: </h3>
    <img style="width:50%;height:20%" class="img img-thumbnail" src="{{ books.cover.url }}"> 

</p>

</div>

{% endblock contents %}

reviews/templates/reviews/details.html
{% extends 'reviews/base.html' %}

{% block title %} {{books.title}} {% endblock title %}
{% block contents %}
<p>
    <h3>Book Title:{{books.title}}</h3></p>
<br>
<p>Publication Date: {{books.publication_date}}</p>
<br>
<p>ISBN: {{books.isbn}}</p>
<p> 
    <h3>Book Cover: </h3>
    <img style="width:50%;height:20%" class="img img-thumbnail" src="{{ books.cover.url }}"> 

</p>
<p>
    <h3>Download</h3>
   <a href="{% url 'download_pdf' pk=books.pk %}">Download PDF</a>
</p>
<div class="col-md-4">
<p>Check other books by the same other</p>


    {% for contributor in cont %}
   
<h4> {{contributor.role}} </h4>
<h4> {{contributor.contributor}} </h4>



{%empty%}

<h4> No Contributor found </h4>

{% endfor %}

</div>

{% for allBook in allBooks %}
<p> {{allBook.title}} </p>
<img style="width:30%;height:20%" class="img img-thumbnail" src="{{ allBook.cover.url }}"> 


{% endfor %}

<form method="post" action="{% url 'details' books.id %}">
    {% csrf_token %}
<p>
<label for="id_review_text">Your Review</label><br/>
<textarea id="id_review_text" name="review_text"
placeholder="Enter your review"></textarea>
</p>
<p>
<label for="id_rating">Rating</label><br/>
<input id="id_rating" type="number" name="rating"
placeholder="Rating 1-5">
</p>
<p>
<button type="submit">Create Review</button>
</p>
</form>



{% endblock contents %}

reviews/templates/reviews/forms.html
<form method="post">
    <p>
        <label for="id_text_input">Text Input</label><br>
        <input id="id_text_input" type="text"
        name="text_input" value="" placeholder=
        "Enter some text">
        </p>
        <p>
        <label for="id_password_input">Password Input
        </label><br>
        <input id="id_password_input" type="password"
        name="password_input" value="" placeholder="Your
        password">
        </p>

        <p>
            <input id="id_checkbox_input" type="checkbox"
            name="checkbox_on" value="Checkbox Checked"
            checked>
            <label for="id_checkbox_input">Checkbox</label>
            </p>
            <p>
            <input id="id_radio_one_input" type="radio"name="radio_input" value="Value One">
            <label for="id_radio_one_input">Value One</label>
            <input id="id_radio_two_input" type="radio"
            name="radio_input" value="Value Two" checked>
            <label for="id_radio_two_input">Value Two</label>
            <input id="id_radio_three_input" type="radio"
            name="radio_input" value="Value Three">
            <label for="id_radio_three_input">Value Three
            </label>
            </p>
            <p>
                <label for="id_favorite_book">Favorite Book
                </label><br>
                <select id="id_favorite_book" name=
                "favorite_book">
                <optgroup label="Non-Fiction">
                <option value="1">Deep Learning with
                Keras</option>
                <option value="2">Web Development with
                Django</option>
                </optgroup>
                <optgroup label="Fiction">
                <option value="3">Brave New World</option>
                <option value="4">The Great
                Gatsby</option>
                </optgroup>
                </select>
                </p>
                <p>
                    <label for="id_books_you_own">Books You Own
                    </label><br>
                    <select id="id_books_you_own" name="books_you_own"
                    multiple>
                    <optgroup label="Non-Fiction">
                    <option value="1">Deep Learning with
                    Keras</option>
                    <option value="2">Web Development with
                    Django</option>
                    </optgroup>
                    <optgroup label="Fiction">
                    <option value="3">Brave New World</option>
                    <option value="4">The Great Gatsby
                    </option>
                    </optgroup>
                    </select>
                    </p>
                    <p>
                        <label for="id_text_area">Text Area</label><br>
                        <textarea name="text_area" id="id_text_area"
                        placeholder="Enter multiple lines of text">
                        </textarea>
                        </p>
                        <p>
                            <label for="id_number_input">Number Input
                            </label><br>
                            <input id="id_number_input" type="number"
                            name="number_input" value="" step="any"
                            placeholder="A number">
                            </p>
                            <p>
                            <label for="id_email_input">Email Input
                            </label><br>
                            <input id="id_email_input" type="email"
                            name="email_input" value="" placeholder="Your
                            email address">
                            </p>
                            <p>
                            <label for="id_date_input">Date Input</label><br>
                            <input id="id_date_input" type="date"
                            name="date_input" value="2019-11-23">
                            </p>
                            <p>
                                <input type="submit" name="submit_input"
                                value="Submit Input">
                                </p>
                                <p>
                                <button type="submit" name="button_element"
                                value="Button Element">Button With<strong>
                                Styled</strong> Text
                                </button>
                                </p>
                                <input type="hidden" name="hidden_input" value="Hidden
Value">
</form>

reviews/templates/reviews/login.html
{% extends 'reviews/base.html' %}

{% block title %}Login Page{% endblock title %}

{% block contents %}


<div class="container">
    
    <div class="b-example-divider"></div>

    <div class="container col-xl-10 col-xxl-8 px-4 py-5">
      <div class="row align-items-center g-lg-5 py-5">
        <div class="col-lg-7 text-center text-lg-start">
          <h1 class="display-4 fw-bold lh-1 mb-3">Vertically centered hero sign-up form</h1>
          <p class="col-lg-10 fs-4">Below is an example form built entirely with Bootstrap&apos;s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
        </div>
        <div class="col-md-10 mx-auto col-lg-5">
          <form class="p-4 p-md-5 border rounded-3 bg-light " method="POST">
            {% csrf_token %}
            <div class="form-floating mb-3">
              <input type="text" name="username" class="form-control" id="floatingInput" placeholder="Username">
              <label for="floatingInput">Username</label>
            </div>
            <div class="form-floating mb-3">
              <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
              <label for="floatingPassword">Password</label>
            </div>
            <div class="checkbox mb-3">
              <label>
                <input type="checkbox" value="remember-me"> Remember me
              </label>
            </div>
            {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
            <hr class="my-4">
        <small class="text-muted">Don't have an account?</small>
          <a type="btn btn-outline-primary" href="{% url 'register' %} ">Sign Up</a>
          </form>
        </div>
      </div>
    </div>


</div>
{% endblock contents %}

reviews/templates/reviews/profile.html
{% extends 'reviews/base.html' %}

{% block contents %}


<div class="container">

{% if user %}


<h2>{{profile | title}} Books Uploaded</h2>
<a class="btn btn-primary" href="{% url 'upload' user.id %}">Upload a Book</a>

<div>
<p>You have a total of <span class="badge rounded-pill bg-primary">{{book_count}}</span> Books </p>

</div>
{% for books in uploaded_books %}

{{forloop.counter}} <p>Title: {{ books.title }}</p>

    <h3>Book Cover: </h3>
    
    <div class="row">
    <div class="col-lg-4 col-md-4">
        
    <img style="" class="img img-thumbnail" src="{{ books.cover.url }}"> 
    </div>
    <br>
   <p> <a href="{% url 'book_details' books.id %}" class="btn btn-primary"> Details</a>
    <a href="{% url 'update' books.id %}" class="btn btn-success"> Update</a>
     <a href="{% url 'delete' books.id %}" class="btn btn-danger"> Delete</a></p>
{%empty%}
<p>Books uploaded will show here</p>
<p> You have no Books Uploaded cuurently</p>
    {% endfor %}

   
    </div><!--ends row-->
</div><!--ends container-->





{% endif %}
</div>
{% endblock contents %}

reviews/templates/reviews/register.html
{% extends 'reviews/base.html' %}

{% block title %}Register Page{% endblock title %}

{% block contents %}
<div class="b-example-divider"></div>

<div class="container col-xl-10 col-xxl-8 px-4 py-5">
  <div class="row align-items-center g-lg-5 py-5">
    <div class="col-lg-5 text-center text-lg-start">
      <h1 class="display-4 fw-bold lh-1 mb-3">Bookr </h1>
      <p class="col-lg-10 fs-4">Adipisci libero obcaecati culpa quidem minus laboriosam tempora, quaerat nulla obcaecati placeat sed aliquid optio vero nemo incidunt illo ratione, quod vel voluptatum unde ab accusantium amet modi optio dignissimos? </p>
    </div>
    <div class="col-md-10 mx-auto col-lg-7">
      <form class="p-4 p-md-5 border rounded-3 bg-light" method="POST">
        <div class="form-floating mb-3">
           
                <h5> Create An Account</h5>
                {% csrf_token %}
                
                {{form.as_p}}
                
                <input type="submit" class="btn btn-primary" value="Register">
                <p class="text-center">Have an account? <br>
                    <a href="{% url 'login' %}">Login</a>
                
               
        <hr class="my-4">
        <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
      </form>
    </div>
  </div>
</div>
<div class="container">

</div>
{% endblock contents %}